services:
  embeddings:
    build:
      context: .
      dockerfile: Dockerfile.embeddings
    ports:
      - 8080:8080
    volumes:
      - ../models:/models
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 600s
      timeout: 5s
      retries: 5
      # Allows for initial model downloads
      # In a production environment, you likely want to pre-cache the embedding model
      start_period: 100000s
      start_interval: 5s

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - qdrant_storage:/qdrant/storage
    healthcheck:
      test:
        - CMD-SHELL
        - bash -c ':> /dev/tcp/127.0.0.1/6333' || exit 1
      interval: 600s
      timeout: 5s
      retries: 5
      start_period: 100000s
      start_interval: 5s

  client:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      embeddings:
        condition: service_healthy
      qdrant:
        condition: service_healthy
    restart: "no"

volumes:
  qdrant_storage:
