#Use this with helm.
#It will create pods for open-webui and expose port 30990 on your cluster; for the UI.
replicaCount: 1

ollama:
  enabled: true
  ollama:
    models:
      pull:
        - llama3.2:1b
      run:
        - llama3.2:1b
    gpu:
       enabled: true
       type: 'nvidia'
       number: 1
  resources:
    requests:
      cpu: 1000m
      memory: 5Gi
    limits:
      cpu: 2500m
      memory: 8Gi
      nvidia.com/gpu: 1

pipelines:
  enabled: false

persistence:
  enabled: true
  size: 10Gi
  accessModes:
     - ReadWriteOnce
  storageClass: local-path

service:
  type: NodePort
  port: 8080
  nodePort: 30990