#Use this with helm.
#It will create pods for open-webui and expose port 30990 on your cluster; for the UI.
replicaCount: 1

ollama:
  enabled: true
  image:
    repository: ollama/ollama
    tag: "0.3.14"
  ollama:
    models:
      pull:
        - llama3.2:1b
      run:
        - llama3.2:1b
  resources:
    requests:
      cpu: 1000m
      memory: 5Gi
    limits:
      cpu: 2500m
      memory: 8Gi

pipelines:
  enabled: false

persistence:
  enabled: true
  size: 10Gi
  accessModes:
     - ReadWriteOnce
  storageClass: local-path

service:
  type: NodePort
  port: 8080
  nodePort: 30990