services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.1.2 #
    container_name: mealie
    restart: always
    ports:
        - "9000:9000" #
    deploy:
      resources:
        limits:
          memory: 1000M #
    volumes:
      - mealie-data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris

volumes:
  mealie-data:
